package com.orangefox.unofficial.ui.theme

import androidx.compose.ui.graphics.Color

// Brand
val FoxOrange = Color(0xFFFF6D00)
val FoxOrangeDeep = Color(0xFFE65100)

// Light scheme (Fox Orange — Material 3 tonal palette)
val LightPrimary = Color(0xFF9A4600)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDBC8)
val LightOnPrimaryContainer = Color(0xFF341100)
val LightSecondary = Color(0xFF765848)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDCC5)
val LightOnSecondaryContainer = Color(0xFF2B170A)
val LightTertiary = Color(0xFF636032)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFEAE5AB)
val LightOnTertiaryContainer = Color(0xFF1E1C00)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F6)
val LightOnBackground = Color(0xFF201A17)
val LightSurface = Color(0xFFFFF8F6)
val LightOnSurface = Color(0xFF201A17)
val LightSurfaceVariant = Color(0xFFF4DED2)
val LightOnSurfaceVariant = Color(0xFF52443B)
val LightOutline = Color(0xFF857367)
val LightOutlineVariant = Color(0xFFD7C2B5)
val LightInverseSurface = Color(0xFF352F2B)
val LightInverseOnSurface = Color(0xFFFBEEE9)
val LightInversePrimary = Color(0xFFFFB68C)

// Dark scheme (Fox Orange — deep warm dark)
val DarkPrimary = Color(0xFFFFB68C)
val DarkOnPrimary = Color(0xFF542200)
val DarkPrimaryContainer = Color(0xFF773300)
val DarkOnPrimaryContainer = Color(0xFFFFDBC8)
val DarkSecondary = Color(0xFFE6BFA6)
val DarkOnSecondary = Color(0xFF432B1B)
val DarkSecondaryContainer = Color(0xFF5C4030)
val DarkOnSecondaryContainer = Color(0xFFFFDCC5)
val DarkTertiary = Color(0xFFCEC990)
val DarkOnTertiary = Color(0xFF343200)
val DarkTertiaryContainer = Color(0xFF4B4900)
val DarkOnTertiaryContainer = Color(0xFFEAE5AB)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1310)
val DarkOnBackground = Color(0xFFEFE0D9)
val DarkSurface = Color(0xFF1A1310)
val DarkOnSurface = Color(0xFFEFE0D9)
val DarkSurfaceVariant = Color(0xFF52443B)
val DarkOnSurfaceVariant = Color(0xFFD7C2B5)
val DarkOutline = Color(0xFF9F8D81)
val DarkOutlineVariant = Color(0xFF52443B)
val DarkInverseSurface = Color(0xFFEFE0D9)
val DarkInverseOnSurface = Color(0xFF352F2B)
val DarkInversePrimary = Color(0xFF9A4600)
